package dev.denza.apps.feature.cloud

import org.json.JSONArray
import org.junit.Assert.*
import org.junit.Test

/** Generated by actual Java guardian serializers, with synthetic workers and no vehicle data. */
class CloudRuntimeWireContractTest {
    @Test fun applicationConsumesActualAwakeGuardianResponses() {
        consume("protocol3-responses.json", 14, allowLegacyCleanup = true)
    }

    @Test fun legacyGuardianResponsesRemainCleanupOnly() {
        consume("protocol2-responses.json", 9, allowLegacyCleanup = true)
    }

    private fun consume(resource: String, count: Int, allowLegacyCleanup: Boolean) {
        val text = checkNotNull(javaClass.getResourceAsStream("/cloud/$resource"))
            .bufferedReader().use { it.readText() }
        val cases = JSONArray(text)
        assertEquals(count, cases.length())
        for (index in 0 until cases.length()) {
            val fixture = cases.getJSONObject(index)
            val response = fixture.getJSONObject("response")
            val id = response.getLong("id")
            val op = response.getString("op")
            if (response.getInt("protocol") == 2 && op !in setOf("PROBE", "STATUS", "STOP")) {
                assertThrows(IllegalStateException::class.java) {
                    CloudCustomProtocol.answer(response.toString(), id, op, allowLegacyCleanup)
                }
                continue
            }
            if (response.getBoolean("ok")) {
                val status = CloudCustomProtocol.answer(response.toString(), id, op, allowLegacyCleanup)
                assertEquals(fixture.getString("name"), response.getString("code"), status.code)
                assertEquals(response.getBoolean("session_live"), status.sessionLive)
                if (response.getInt("protocol") == 3) {
                    assertEquals(CloudCustomProtocol.PROFILE, status.profile)
                    assertEquals(response.getBoolean("lease_active"), status.leaseActive)
                    assertEquals(response.getLong("lease_until_uptime_ms"), status.leaseUntilUptimeMs)
                }
            } else {
                val error = assertThrows(CloudCustomRejected::class.java) {
                    CloudCustomProtocol.answer(response.toString(), id, op, allowLegacyCleanup)
                }
                assertEquals(response.getString("code"), error.code)
                assertEquals(response.getBoolean("retryable"), error.retryable)
            }
        }
    }
}
